open-meteo:
  url: ${OPEN_METEO_URL}
  historical-data-endpoint: ${OPEN_METEO_HISTORICAL_DATA_ENDPOINT}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop